version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: fintrack_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5442:5432"
    volumes:
      - ./Scripts:/docker-entrypoint-initdb.d
    networks:
      - fintrack-net

  webapi:
    build:
      context: ../../
      dockerfile: Docker/Local/Dockerfile
    container_name: fintrack_api
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Local
      ConnectionStrings__Default: "Host=postgres;Port=5432;Username=admin;Password=admin;Database=fintrack"
    ports:
      - "7019:8080"
    networks:
      - fintrack-net

networks:
  fintrack-net:
    driver: bridge
