services:
  postgres:
    image: postgres:16
    container_name: fintrack_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5442:5432"
    volumes:
      - ./Scripts:/docker-entrypoint-initdb.d
    networks:
      - fintrack-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  fintrack-net:
    external: true